services:
  app:
    image: gradle
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: ./gradlew bootRun
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backup:
    image: postgres
    environment:
      PGPASSWORD: ${DB_PASSWORD}
    entrypoint: >
      sh -c "pg_dump -h db -U ${DB_USER} ${DB_NAME} > /backup/backup$(date +%e-%m-%Y_%H-%M).sql"
    volumes:
      - ./db-backup:/backup
    depends_on:
      - db

volumes:
  postgres_data:
